/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportIndexRouteImport } from './routes/transport.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as ShipmentsJobNoRouteImport } from './routes/shipments.$jobNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIndexRoute = TransportIndexRouteImport.update({
  id: '/transport/',
  path: '/transport/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsJobNoRoute = ShipmentsJobNoRouteImport.update({
  id: '/shipments/$jobNo',
  path: '/shipments/$jobNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shipments/$jobNo': typeof ShipmentsJobNoRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/transport/': typeof TransportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shipments/$jobNo': typeof ShipmentsJobNoRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/transport': typeof TransportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shipments/$jobNo': typeof ShipmentsJobNoRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/transport/': typeof TransportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shipments/$jobNo'
    | '/analytics/'
    | '/clients/'
    | '/documents/'
    | '/invoices/'
    | '/shipments/'
    | '/tasks/'
    | '/transport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shipments/$jobNo'
    | '/analytics'
    | '/clients'
    | '/documents'
    | '/invoices'
    | '/shipments'
    | '/tasks'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/shipments/$jobNo'
    | '/analytics/'
    | '/clients/'
    | '/documents/'
    | '/invoices/'
    | '/shipments/'
    | '/tasks/'
    | '/transport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShipmentsJobNoRoute: typeof ShipmentsJobNoRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TransportIndexRoute: typeof TransportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/': {
      id: '/transport/'
      path: '/transport'
      fullPath: '/transport/'
      preLoaderRoute: typeof TransportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/$jobNo': {
      id: '/shipments/$jobNo'
      path: '/shipments/$jobNo'
      fullPath: '/shipments/$jobNo'
      preLoaderRoute: typeof ShipmentsJobNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShipmentsJobNoRoute: ShipmentsJobNoRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TransportIndexRoute: TransportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
